name: 'Quality assurance pipeline'

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    container: giomba/ceda-rom-disassembly:1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and test
        run: |
          make assemble
          make tests

